let portfolo_data = [
  {
    work_thub_: "img/KYWA.png",
    people: "1",
    title_: "KYWA 리뉴얼",
    date_: "5일",
    use_program: "Vscode , Figma",
    part: "100%",
    img_: "img/KYWA_FULL.png",
    href: "https://siblin123.github.io/KYWA/",
    Demo_: "https://siblin123.github.io/KYWA/",
    Github_: "https://github.com/Siblin123/KYWA",
    responsive: "제작"
  },
  {
    work_thub_: "img/lotte world.png",
    people: "3",
    title_: "롯대 아쿠아리움",
    date_: "5일",
    use_program: "Vscode , Figma",
    part: "헤더,메인 비주얼 <br>전시생물,티켓 예매",
    img_: "img/lotte world FULL.jpg",
    href: "https://siblin123.github.io/aquarium/",
    Demo_: "https://siblin123.github.io/aquarium/",
    Github_: "https://github.com/Siblin123/aquarium",
    responsive: "제작"
  },
  {
    work_thub_: "img/Music.png",
    people: "1",
    title_: "대관령 음악제",
    date_: "5일",
    use_program: "Vscode , Figma",
    part: "100%",
    img_: "img/Daegwallyeong.png",
    href: "https://siblin123.github.io/Daegwallyeong-Music-Festival/",
    Demo_: "https://siblin123.github.io/Daegwallyeong-Music-Festival/",
    Github_: "https://github.com/Siblin123/Daegwallyeong-Music-Festival",
    responsive: "제작"
  },
  {
    work_thub_: "img/AirClass.png",
    people: "1",
    title_: "AirClass",
    date_: "5일",
    use_program: "Vscode , Figma",
    part: "100%",
    img_: "img/AirClass_FULL.png",
    href: "https://siblin123.github.io/AirClass/",
    Demo_: "https://siblin123.github.io/AirClass/",
    Github_: "https://github.com/Siblin123/AirClass",
    responsive: "제작"
  },
    {
    work_thub_: "img/maniker_main.png",
    people: "1",
    title_: "maniker",
    date_: "2일",
    use_program: "Vscode",
    part: "100%",
    img_: "img/miniker_Full.JPG",
    href: "https://siblin123.github.io/maniker/",
    Demo_: "https://siblin123.github.io/maniker/",
    Github_: "https://github.com/Siblin123/maniker",
    responsive: "제작"
  },
];
